In [2]:
a=[(1,3),(2,4)]

In [4]:
import numpy as np
b= np.array(a)
print(b)
print(type(b))

[[1 3]
 [2 4]]
<class 'numpy.ndarray'>


In [5]:
import numpy
b=np.array(a)
print(b)
print(type(b))

[[1 3]
 [2 4]]
<class 'numpy.ndarray'>


In [6]:
print(b*b)

[[ 1  9]
 [ 4 16]]


In [7]:
c=np.matrix(b)
print(type(c))

<class 'numpy.matrixlib.defmatrix.matrix'>


In [9]:
print(c)

[[1 3]
 [2 4]]


In [8]:
print(c*c)

[[ 7 15]
 [10 22]]


In [10]:
a=[(1,2,3),(9,8,7)]

In [11]:
import numpy
b=numpy.array(a)
print(b); print(type(b))

[[1 2 3]
 [9 8 7]]
<class 'numpy.ndarray'>


In [13]:
c=numpy.matrix(b)
print(c); print(type(c))

[[1 2 3]
 [9 8 7]]
<class 'numpy.matrixlib.defmatrix.matrix'>


In [14]:
b*b

array([[ 1,  4,  9],
       [81, 64, 49]])

In [15]:
c*c

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [16]:
print(c*c.T)

[[ 14  46]
 [ 46 194]]


In [17]:
a="home"; list(a)

['h', 'o', 'm', 'e']

In [18]:
print(a[0])

h


In [22]:
a={"1":"sun","2":"moon","3":"star","4":"clouds"}
a["3"]

'star'

In [27]:
a=[10,9,8,7,6,5,4,3,2,1]
for i in a:
    print(i)

10
9
8
7
6
5
4
3
2
1


In [32]:
a=[10,9,8,7,6,5,4,3,2,1]
for i in range(len(a)):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [33]:
print(i+1)

10


In [36]:
a=["A","B","C"]
b=[3,4,5]
for i,a in enumerate(a):
    print("{} {}s".format(b[i],a))

3 As
4 Bs
5 Cs


In [41]:
a=["A","B","C"]
b=[3,4,5]
for x,y in zip(a,b):
     print("{} {}s".format(y,x))

3 As
4 Bs
5 Cs


In [44]:
a=1; 
if a==1:
    print("yes")
else: print("no")

yes


In [45]:
a="white"
print(a[1:2]); print(a[0:4])

h
whit


In [47]:
a=["b","l","a","c","k"]
print(a[1:3])

['l', 'a']


In [48]:
a[0]+a[2]+a[3]+a[4]

'back'

In [50]:
a="black"

In [51]:
a.upper()

'BLACK'

In [66]:
a=a[0]+a[2]+a[3]+a[4]
print(a)

back


In [55]:
a.upper()

'BACK'

In [77]:
a="a book is on the desk"
len(a)

21

In [78]:
x=a.find('book')
x

2

In [80]:
y=a.rindex('the')
y

13

In [83]:
z= a.split()
z

['a', 'book', 'is', 'on', 'the', 'desk']

In [86]:
' '.join(z)

'a book is on the desk'

In [87]:
a.replace("book","pencil")

'a pencil is on the desk'